task_tracking/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("tasks.urls")),
    path('accounts/login', auth_views.LoginView.as_view(), name ="login"),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

tasks/urls.py
from django.urls import path
from tasks import views

urlpatterns = [
    path('', views.TaskListView.as_view(),name="task-list"),
    path('<int:pk>/', views.TaskDetailView.as_view(),name="task-details"),
    path('<int:pk>/update/', views.TaskUpdateView.as_view(),name="task-update"),
    path('<int:pk>/delete/', views.TaskDeleteView.as_view(),name="task-delete"),
    path('task-create', views.TaskCreateView.as_view(), name = "task-create"),
    path('<int:pk>/complete', views.TaskCompleteView.as_view(), name = "task-complete"),
    path('comment/edit/<int:pk>/', views.CommentEditView.as_view(), name='edit-comment'),
    path('comment/delete/<int:pk>/', views.CommentDeleteView.as_view(), name='delete-comment'),
    path('comment/like/<int:pk>/', views.CommentLikesView.as_view(), name='like-comment'),
    path("login/", views.CustomLoginView.as_view(), name="login"),
    path("logout/", views.CustomLogoutView.as_view(), name="logout"),
    path("register/", views.RegisterView.as_view(), name="register"),
]
app_name = "tasks"

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Система управління завданнями</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a href="{% url 'tasks:task-list' %}" class = "navbar-brand">Головна</a>
        <a href="{% url 'tasks:register' %}" class = "navbar-brand">Реєстрація</a>
        <p class="position-absolute top-5 end-100">{{request.user.username}}</p>
        
    <form action = "{% url 'tasks:logout' %}"method = "post">
        {% csrf_token %}        
        <button class="btn btn-light position-absolute top-5 end-0 translate-middle-y" type="submit">Вихід</button>
    </form>

    </nav>
    {% block content%}

    {% endblock %}
</body>

</html>